//! Bearer-token store for `aborad`.
//!
//! Tokens are stored as **SHA-256 hashes**, never as plaintext, in a
//! dedicated TOML file referenced by `[security] token_file`. It must not
//! be world-readable: mode `0600` when `aborad` runs as the file's owner,
//! or `root:aborad` mode `0640` when it runs as the `aborad` service user. Incoming `Authorization: Bearer` secrets are
//! hashed and compared in constant time; the secret itself can never be
//! recovered from the file.
//!
//! File format (generated by `abora auth generate-token`):
//!
//! ```toml
//! [[tokens]]
//! name = "operator"
//! permissions = ["read_all"]              # or e.g. ["read:health", "read:system"]
//! secret_hash = "sha256:<64 hex chars>"
//! ```
//!
//! The special permission `read_all` grants every `read:*` permission and is
//! the right choice for a local read-only operator or monitoring agent. It never
//! grants a mutating permission: `manage:updates` (applying updates) must be
//! named explicitly.

#![forbid(unsafe_code)]

use std::path::Path;

use sha2::{Digest, Sha256};

/// Errors while loading or parsing a token file.
#[derive(Debug, thiserror::Error)]
pub enum TokenStoreError {
    #[error("could not read token file `{token_file}`: {source}")]
    Io {
        token_file: std::path::PathBuf,
        source: std::io::Error,
    },
    #[error("token file `{token_file}`: {message}")]
    BadEntry {
        token_file: std::path::PathBuf,
        message: String,
    },
}

/// A token record after successful authentication.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StoredToken {
    /// Optional human-readable label (audit logs).
    pub name: Option<String>,
    /// Permission ids this token grants. `read_all` grants every `read:*` permission.
    pub permissions: Vec<String>,
}

impl StoredToken {
    /// Whether this token grants `permission_id`. `read_all` covers every `read:*` permission and
    /// nothing else: mutating permissions (`manage:*`) must be named explicitly.
    pub fn grants(&self, permission_id: &str) -> bool {
        self.permissions
            .iter()
            .any(|p| p == permission_id || (p == "read_all" && permission_id.starts_with("read:")))
    }
}

#[derive(Debug, Clone)]
struct Entry {
    token: StoredToken,
    hash: [u8; 32],
}

/// An immutable, in-memory view of a token file.
#[derive(Debug, Clone, Default)]
pub struct TokenStore {
    entries: Vec<Entry>,
}

#[derive(serde::Deserialize)]
struct RawFile {
    #[serde(default)]
    tokens: Vec<RawToken>,
}

#[derive(serde::Deserialize)]
struct RawToken {
    #[serde(default)]
    name: Option<String>,
    #[serde(default)]
    permissions: Vec<String>,
    secret_hash: String,
}

impl TokenStore {
    /// Load and parse the token file at `path`.
    pub fn load(path: &Path) -> Result<Self, TokenStoreError> {
        let raw = std::fs::read_to_string(path).map_err(|source| TokenStoreError::Io {
            token_file: path.to_path_buf(),
            source,
        })?;
        Self::from_str(&raw).map_err(|message| TokenStoreError::BadEntry {
            token_file: path.to_path_buf(),
            message,
        })
    }

    /// Parse a token file from a TOML string.
    pub fn from_str(text: &str) -> Result<Self, String> {
        let raw: RawFile = toml::from_str(text).map_err(|e| format!("invalid TOML: {e}"))?;
        let mut entries = Vec::with_capacity(raw.tokens.len());
        for token in raw.tokens {
            let hash = decode_sha256_hex(&token.secret_hash)?;
            entries.push(Entry {
                token: StoredToken {
                    name: token.name,
                    permissions: token.permissions,
                },
                hash,
            });
        }
        Ok(Self { entries })
    }

    /// Number of configured tokens.
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Look up a bearer secret, returning its token record. The secret is
    /// hashed and compared in constant time; unknown secrets return `None`
    /// (never leaking whether a token exists).
    pub fn find(&self, bearer: &str) -> Option<&StoredToken> {
        let digest = Sha256::digest(bearer.as_bytes());
        let hash: [u8; 32] = digest.into();
        self.entries
            .iter()
            .find(|e| ct_eq(&e.hash, &hash))
            .map(|e| &e.token)
    }
}

/// `sha256:` + hex of a secret. Test-only: the daemon itself hashes inline
/// via [`TokenStore::find`], and tokens are generated by `abora auth
/// generate-token` (its own copy of this helper).
#[cfg(test)]
pub fn sha256_hex(secret: &str) -> String {
    let digest = Sha256::digest(secret.as_bytes());
    let hash: [u8; 32] = digest.into();
    format!("sha256:{}", hex_encode(&hash))
}

fn decode_sha256_hex(prefixed: &str) -> Result<[u8; 32], String> {
    let (scheme, hex) = prefixed
        .split_once(':')
        .ok_or_else(|| format!("secret_hash must look like `sha256:<64 hex>`, got `{prefixed}`"))?;
    if scheme != "sha256" {
        return Err(format!(
            "unsupported secret_hash scheme `{scheme}` (expected sha256)"
        ));
    }
    if hex.len() != 64 {
        return Err(format!(
            "secret_hash must be exactly 64 hex characters, got {}",
            hex.len()
        ));
    }
    let mut out = [0u8; 32];
    for (i, byte) in out.iter_mut().enumerate() {
        let pair = &hex[i * 2..i * 2 + 2];
        *byte = u8::from_str_radix(pair, 16)
            .map_err(|_| format!("secret_hash contains non-hex characters: `{pair}`"))?;
    }
    Ok(out)
}

#[cfg(test)]
fn hex_encode(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut out = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        out.push(HEX[(byte >> 4) as usize] as char);
        out.push(HEX[(byte & 0x0f) as usize] as char);
    }
    out
}

/// Constant-time comparison of fixed-size hashes: the loop length never
/// depends on the input, so timing does not leak which bytes matched.
fn ct_eq(a: &[u8; 32], b: &[u8; 32]) -> bool {
    let mut diff = 0u8;
    for (x, y) in a.iter().zip(b.iter()) {
        diff |= x ^ y;
    }
    diff == 0
}

#[cfg(test)]
mod tests {
    use super::*;

    fn store(secret: &str, permissions: &[&str], name: &str) -> TokenStore {
        let perms = permissions
            .iter()
            .map(|p| format!("\"{p}\""))
            .collect::<Vec<_>>()
            .join(", ");
        let hash = sha256_hex(secret);
        let toml = format!(
            "[[tokens]]\nname = \"{name}\"\npermissions = [{perms}]\nsecret_hash = \"{hash}\"\n"
        );
        TokenStore::from_str(&toml).unwrap()
    }

    #[test]
    fn finds_token_by_exact_secret() {
        let store = store("s3cret", &["read:health"], "op");
        let found = store.find("s3cret").unwrap();
        assert_eq!(found.name.as_deref(), Some("op"));
        assert!(found.grants("read:health"));
    }

    #[test]
    fn unknown_and_wrong_secrets_are_not_found() {
        let store = store("correct-horse", &["read:health"], "op");
        assert!(store.find("battery-staple").is_none());
        assert!(store.find("").is_none());
        assert!(store.find(" correct-horse").is_none());
        assert!(store.find("correct-horse ").is_none());
    }

    #[test]
    fn read_all_grants_any_permission() {
        let store = store("root", &["read_all"], "operator");
        for id in ["read:health", "read:version", "read:system", "read:updates"] {
            assert!(store.find("root").unwrap().grants(id), "{id}");
        }
    }

    #[test]
    fn empty_permissions_grant_nothing() {
        let store = store("x", &[], "nobody");
        assert!(!store.find("x").unwrap().grants("read:health"));
    }

    #[test]
    fn malformed_files_are_rejected() {
        assert!(TokenStore::from_str("not toml [[[[").is_err());
        assert!(TokenStore::from_str("[tokens]\nsecret_hash = \"md5:abc\"\n").is_err());
        assert!(TokenStore::from_str("[[tokens]]\nsecret_hash = \"sha256:short\"\n").is_err());
        assert!(TokenStore::from_str(
            "[[tokens]]\nsecret_hash = \"sha256:zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz\"\n"
        )
        .is_err());
    }

    #[test]
    fn empty_file_is_valid_but_useless() {
        let store = TokenStore::from_str("").unwrap();
        assert!(store.is_empty());
        assert_eq!(store.len(), 0);
        assert!(store.find("anything").is_none());
    }

    #[test]
    fn collision_behavior_is_sound() {
        // Only a byte-for-byte identical hash matches (constant time).
        let store = store(
            "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            &["read_all"],
            "a",
        );
        assert!(store
            .find("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab")
            .is_none());
    }
}
